Test exercises done
K-Danils/06-2021 pull request #10
Opened 2022-01-03 21:56 UTC by K-Danils

2022-01-04 15:00 UTC, ausmoons requested changes

2022-01-04 15:00 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/exercise1/Program.cs
>              if (num1 == 15 || num2 == 15)
return uzreiz

2022-01-04 15:00 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/exercise8/Program.cs
> +
Pietiek ar vienu tukšu rindu

2022-01-04 15:00 UTC, ausmoons commented on csharp-basics/exercises/Arrays/RandomArrays.Tests/Exercise6Test.cs
> +            _target = new RandomArrays();
// Arrange // Act // Assert

2022-01-04 15:00 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Account/Account.cs
> +        public static void Transfer(AccountCreator from, AccountCreator to, double howMuch)
Transfer bija jābūt galvenajā klasē. Tā ir darbība starp 2 dažādiem account

2022-01-04 15:00 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/ClassesAndObjectsTests/AccountTest.cs
> +            _target = new AccountCreator("a", 90);
// Arrange // Act // Assert

2022-01-04 15:00 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/ClassesAndObjectsTests/DateTEst.cs
> +            try
testā neliek try/catch

2022-01-04 15:00 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/Exercise5/Date.cs
> +        private int _day { get; set; }
bez get/set

2022-01-04 15:00 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/DragRace/Program.cs
> +                    if (i == 3)
else if, jo vienlaicīgi nevar būt 1 un 3

2022-01-04 15:00 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/DragRaceTests/BoostableCarTest.cs
> +            Assert.AreEqual(50.ToString(), _target.ShowCurrentSpeed());
50.ToString() - kāpēc pie arrange nepieliec jau vajadzīgo stringu?

2022-01-04 15:00 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/DragRaceTests/NonBoostableCarTest.cs
> +            for (int i = 0; i < speedUpTimes; i++)
Lai nav visu laiku loop jātaisa, metodē varēja ielikt parametru ar reižu skaitu, ja nu kas.

2022-01-04 15:00 UTC, ausmoons commented on csharp-basics/exercises/Polymorphism/HierarchyTests/TigerTest.cs
> +            _target = new Tiger("Tiger", "Tiger", 180, "Jungle");
Visur pieliec // Arrange // Act // Assert

2022-01-06 14:31 UTC, K-Danils commented on csharp-basics/exercises/Polymorphism/DragRaceTests/NonBoostableCarTest.cs
> +            for (int i = 0; i < speedUpTimes; i++)
Jā, bet tas uzreiz sabojās DragRaceSimulation loģiku, izdevīgāk ir vienkārši laist loopus

2022-01-06 19:41 UTC, ausmoons requested changes

2022-01-06 19:41 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/exercise1/Program.cs
> +                num2 - num1 == 15 ? true : false;
Kas tas tāds pēkšņi?

2022-01-06 19:41 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/ClassesAndObjectsTests/DateTEst.cs
> +
Lieka tukša rinda

2022-01-06 19:41 UTC, ausmoons commented on csharp-basics/exercises/ClassesAndObjects/ClassesAndObjectsTests/DateTEst.cs
> +
Lieka tukša rinda. Pārbaudi visus failus

2022-01-08 13:53 UTC, K-Danils commented on csharp-basics/exercises/Arithmetic/exercise1/Program.cs
> +                num2 - num1 == 15 ? true : false;
taisīju return uzreiz, bet aizmirsu, ka ternary operators nav nemaz vajadzīgs, samainīju uz
return num1 == 15 || num2 == 15 || 
                num1 + num2 == 15 || num1 - num2 == 15 || 
                num2 - num1 == 15;

2022-01-08 19:14 UTC, ausmoons approved these changes

2022-01-08 23:17 UTC, merged