Flow control exercises completed
K-Danils/06-2021 pull request #4
Opened 2021-11-27 16:42 UTC by K-Danils

2021-11-28 19:12 UTC, ausmoons requested changes

2021-11-28 19:12 UTC, ausmoons commented on csharp-basics/exercises/FlowOfControl/FlowControl/LargestNumber/Program.cs
> +            {
Lai nav vairākas reizes jātaisa parse vienam un tam pašam inputam, saglabā to iepriekš un izmanto visur kur pēc tam vajag

2021-11-28 19:12 UTC, ausmoons commented on csharp-basics/exercises/TypesAndVariables/Casting/Program.cs
> +            float e = 5f;
Kāpēc mainīji dotos lielumus?

2021-11-29 14:43 UTC, K-Danils commented on csharp-basics/exercises/TypesAndVariables/Casting/Program.cs
> +            float e = 5f;
Aizrāvos ar koda pārrakstīšanu. Ieraudzīju float bez f un double bez .0 un automātiski izlaboju

2021-11-29 19:53 UTC, ausmoons approved these changes

2021-11-29 20:47 UTC, merged