Arrays exercises complete
K-Danils/06-2021 pull request #5
Opened 2021-11-30 12:21 UTC by K-Danils

2021-12-01 16:40 UTC, ausmoons requested changes

2021-12-01 16:40 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/Exercise3/Program.cs
> +            for (int i = 0; i < numbers.Length; i++){
{ jaunā rindā

2021-12-01 16:40 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/Hangman/Program.cs
> +
Lieka tukša rinda. Pārbaudi visus failus

2021-12-01 16:40 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/Hangman/Program.cs
> +
Daudz liekas tukšas rindas

2021-12-01 16:40 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/TicTacToe/Program.cs
> +                return true;
Vienādos return vajag apvienot

2021-12-01 16:40 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/exercise6/Program.cs
> +            Random ran = new Random();
ran?

2021-12-02 10:09 UTC, K-Danils commented on csharp-basics/exercises/Arrays/Arrays/exercise6/Program.cs
> +            Random ran = new Random();
Saīsinājums no Random, number = num, variable = var, column = col, utml.

2021-12-02 18:55 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/exercise6/Program.cs
> +            Random ran = new Random();
labāk lietot pilnos nosaukumus.

2021-12-02 19:16 UTC, ausmoons requested changes

2021-12-02 19:16 UTC, ausmoons commented on csharp-basics/exercises/Arrays/TicTacToe/Program.cs
> +        private static bool isDraw()
Metodes ar lielo burtu

2021-12-02 19:16 UTC, ausmoons commented on csharp-basics/exercises/Arrays/TicTacToe/Program.cs
> +            ){
{ jaunā rindā

2021-12-02 19:16 UTC, ausmoons commented on csharp-basics/exercises/Arrays/TicTacToe/Program.cs
> +            (board[0, 0].Equals(playerSymbol) && board[0, 1].Equals(playerSymbol) && board[0, 2].Equals(playerSymbol)) ||
un vispār var uzreiz return

2021-12-02 19:16 UTC, ausmoons commented on csharp-basics/exercises/Loops/Loops/FizzBuzz/Program.cs
> +        private int num;
_num

2021-12-02 19:16 UTC, ausmoons commented on csharp-basics/exercises/Loops/Loops/NumberSquare/Program.cs
> +        private int min;
_min, _max

2021-12-02 19:16 UTC, ausmoons commented on csharp-basics/exercises/Loops/Loops/exercise3/Program.cs
> +            while (true)
Kurā brīdī izej no loop? Un tu prasi position, bet jāprāsa number

2021-12-02 19:16 UTC, ausmoons commented on csharp-basics/exercises/Loops/Loops/exercise3/Program.cs
> +            for (int i = 0; i < 21; i++)
i <= 20

2021-12-02 19:16 UTC, ausmoons commented on csharp-basics/exercises/Loops/Loops/exercise3/Program.cs
> +            while (true)
Trūkst tukšas rindas

2021-12-03 19:47 UTC, ausmoons approved these changes

2021-12-04 16:07 UTC, merged